routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', [
    'uses' => 'HomeController@index',
    'as' => 'login',
    ])->middleware('auth');

Route::group(['prefix' => LaravelLocalization::setLocale(),'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]], function(){
    Route::group(['prefix' => 'admin','middleware' => 'auth','namespace' => 'Admin'],function(){
        Route::resource('home', 'DashboardController');

        // Categories routes
        Route::get('categories/link', 'CategoriesController@link')->name('categories.link');
        Route::get('categories/create_link', 'CategoriesController@create_link')->name('categories.create_link');
        Route::post('categories/store_link', 'CategoriesController@store_link')->name('categories.store_link');
        Route::get('categories/edit_link/{id}', 'CategoriesController@edit_link')->name('categories.edit_link');
        Route::post('categories/update_link/{id}', 'CategoriesController@update_link')->name('categories.update_link');
        Route::get('categories/show_link/{id}', 'CategoriesController@show_link')->name('categories.show_link');
        Route::post('categories/delete_link/{id}', 'CategoriesController@destroy_link')->name('categories.destroy_link');
        Route::get('categories/activate/{id}', 'CategoriesController@activate')->name('categories.activate');
        Route::get('categories/delete/{id}', 'CategoriesController@delete')->name('categories.delete');
        Route::post('categories/force_delete/{id}', 'CategoriesController@force_delete')->name('categories.force_delete');
        Route::get('deleted_categories', 'CategoriesController@list_deleted')->name('categories.deleted_categories');
        Route::resource('categories', 'CategoriesController');

        // Headcategories routes
        Route::get('headCategories/activate/{id}', 'HeadCategoriesController@activate')->name('headCategories.activate');
        Route::get('headCategories/delete/{id}', 'HeadCategoriesController@delete')->name('headCategories.delete');
        Route::post('headCategories/force_delete/{id}', 'HeadCategoriesController@force_delete')->name('headCategories.force_delete');
        Route::get('deleted_headcategories', 'HeadCategoriesController@list_deleted')->name('headCategories.deleted_headcategories');
        Route::resource('headCategories', 'HeadCategoriesController');

        // BookingTypes routes
        Route::get('bookingTypes/activate/{id}', 'BookingTypesController@activate')->name('bookingTypes.activate');
        Route::get('bookingTypes/link', 'BookingTypesController@link')->name('bookingTypes.link');
        Route::get('bookingTypes/create_link', 'BookingTypesController@create_link')->name('bookingTypes.create_link');
        Route::post('bookingTypes/store_link', 'BookingTypesController@store_link')->name('bookingTypes.store_link');
        Route::get('bookingTypes/edit_link/{id}', 'BookingTypesController@edit_link')->name('bookingTypes.edit_link');
        Route::post('bookingTypes/update_link/{id}', 'BookingTypesController@update_link')->name('bookingTypes.update_link');
        Route::get('bookingTypes/show_link/{id}', 'BookingTypesController@show_link')->name('bookingTypes.show_link');
        Route::post('bookingTypes/destroy_link/{id}', 'BookingTypesController@destroy_link')->name('bookingTypes.destroy_link');
        Route::get('bookingTypes/activate/{id}', 'BookingTypesController@activate')->name('bookingTypes.activate');
        Route::get('bookingTypes/delete/{id}', 'BookingTypesController@delete')->name('bookingTypes.delete');
        Route::post('bookingTypes/force_delete/{id}', 'BookingTypesController@force_delete')->name('bookingTypes.force_delete');
        Route::get('deleted_bookingtypes', 'BookingTypesController@list_deleted')->name('bookingTypes.deleted_bookingtypes');
        Route::resource('bookingTypes', 'BookingTypesController', ['except' => 'delete_link']);

        // settings routes
        Route::resource('settings', 'SettingsController');
        Route::resource('settingTypes', 'SettingTypesController');

        // transactions / mutations routes
        Route::get('transactions/create/{id}', 'TransactionsController@create')->name('transactions.create');
        Route::get('transactions/show/{id}', 'TransactionsController@show')->name('transactions.show');
        Route::get('transactions/pdf/{id}', 'TransactionsController@pdf')->name('transactions.pdf');
        Route::get('mutation_quarters', 'TransactionsController@mutation_quarters')->name('transactions.mutation_quarters');
        Route::post('mutation_quarters', 'TransactionsController@getMutation_quarters')->name('transactions.get_mutation_quarters');
        Route::get('mutations', 'TransactionsController@mutations')->name('transactions.mutations');
        Route::post('mutations', 'TransactionsController@getMutations')->name('transactions.get_mutations');
        Route::resource('transactions', 'TransactionsController', ['except' => 'create']);

        // users, roles and permissions routes
        Route::get('users/activate/{id}', 'UsersController@activate')->name('users.activate');
        Route::get('users/activate_app_user/{id}', 'UsersController@activate_app_user')->name('users.activate_app_user');
        Route::get('users_app', 'UsersController@index_app')->name('users.index_app');
        Route::get('users/users_app/{id}', 'UsersController@show_app')->name('users.show_app');
        Route::get('create_app_user', 'UsersController@create_app_user')->name('users.create_app_user');
        Route::get('users_app/{id}/edit', 'UsersController@edit_app_user')->name('users.edit_app_user');
        Route::post('users/store_app_user', 'UsersController@store_app_user')->name('users.store_app_user');
        Route::get('users/delete/{id}', 'UsersController@delete')->name('users.delete');
        Route::get('users/delete_app_user/{id}', 'UsersController@delete_app_user')->name('users.delete_app_user');
        Route::get('users_app/{id}', 'UsersController@show_app_user')->name('users.show_app');
        Route::post('users_app/{id}', 'UsersController@destroy_app_user')->name('users.destroy_app');
        Route::post('users/update_app_user/{id}', 'UsersController@update_app_user')->name('users.update_app_user');
        Route::post('users/force_delete/{id}', 'UsersController@force_delete')->name('users.force_delete');
        Route::post('users/force_delete_app_user/{id}', 'UsersController@force_delete_app_user')->name('users.force_delete_app_user');
        Route::get('deleted_users', 'UsersController@list_deleted')->name('users.deleted_users');
        Route::get('deleted_app_users', 'UsersController@list_app_users_deleted')->name('users.deleted_app_users');
        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController');
        Route::resource('permissions', 'PermissionsController');

        // Information page routes
        Route::resource('information', 'InformationController');
        Route::get('information_page', 'InformationController@info_page')->name('information.information_page');
    });

    // User routes
    $this->get('admin/new_registrations', 'Admin\UsersController@newRegistrations')->name('users.newRegistrations');
    $this->get('admin/activate_new_user/{id}', 'Admin\UsersController@activateNewUser')->name('users.activateNewUser');

    // Change password routes
    $this->get('admin/changepass', 'Admin\UsersController@changePassword')->name('changepass')->middleware('auth');
    $this->post('admin/changepass', 'Admin\UsersController@updatePassword');

    // Authentication Routes...
    $this->get('admin/login', 'Auth\LoginController@showLoginForm')->name('login');
    $this->post('admin/login', 'Auth\LoginController@login');
    $this->get('admin/logout', 'Auth\LoginController@logout')->name('logout');

    // Password Reset Routes...
    $this->get('admin/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    $this->post('admin/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('admin/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.token');
    $this->post('admin/password/reset', 'Auth\ResetPasswordController@reset');
});

resources/views/admin/bookingTypes/bookingTypes_create.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-11 col-sm-11 col-xs-12">
                            <h2>@lang('bookingTypes.bookingType') </h2>
                        </div>
                        <div class="col-md-1 col-sm-1 col-xs-12 text-right">
                            <a href="{{route('bookingTypes.index')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> @lang('general.nav.back') </a>
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <br />
                    <form method="post" action="{{ route('bookingTypes.store') }}" data-parsley-validate class="form-horizontal form-label-left">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="name">@lang('bookingTypes.name') <span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <input type="text" value="{{ Request::old('name') ?: '' }}" id="name" name="name" class="form-control col-md-7 col-xs-12">
                            @if ($errors->has('name'))
                                    <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="code">@lang('bookingTypes.code') <span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <input type="text" value="{{ Request::old('code') ?: '' }}" id="code_show" class="form-control col-md-7 col-xs-12" disabled>
                                <input type="hidden" value="{{ Request::old('code') ?: '' }}" id="code" name="code" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('code'))
                                    <span class="help-block">{{ $errors->first('code') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="description">@lang('bookingTypes.description') <span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <input type="text" value="{{ Request::old('description') ?: '' }}" id="description" name="description" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('description'))
                                <span class="help-block">{{ $errors->first('description') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('gb_rek') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="gb_rek">@lang('bookingTypes.gb_rek') </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <input type="text" value="{{ Request::old('gb_rek') ?: '' }}" id="gb_rek" name="gb_rek" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('gb_rek'))
                                    <span class="help-block">{{ $errors->first('gb_rek') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('btw_code') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="btw_code">@lang('bookingTypes.btw_code')</label>
                            <div class="col-md-2 col-sm-2 col-xs-12">
                                <select id="btw_code" name="btw_code" class="form-control">
                                        <option value="">@lang('general.app.makechoice')</option>
                                        <option value="0" @if (Request::old('btw_code') == 0 && old('btw_code') != '') {{ 'selected="selected"' }} @endif>0</option>
                                        <option value="3" @if (Request::old('btw_code') == 3) {{ 'selected="selected"' }} @endif>3</option>
                                        <option value="4" @if (Request::old('btw_code') == 4) {{ 'selected="selected"' }} @endif>4</option>
                                </select>
                                @if ($errors->has('btw_code'))
                                    <span class="help-block">{{ $errors->first('btw_code') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="category_id">@lang('categories.category') <span class="required">*</span></label>
                            <div class="col-md-2 col-sm-2 col-xs-12">
                                <select id="category_id" name="category_id" class="form-control">
                                    @if(count($categories))
                                        <option value="">@lang('general.app.makechoice')</option>
                                        @foreach($categories as $row)
                                            <option value="{{$row->id}}" @if ($row->id == Request::old('category_id')) {{ 'selected="selected"' }} @endif>{{$row->name}}</option>
                                        @endforeach
                                    @endif
                                </select>
                                @if ($errors->has('category_id'))
                                    <span class="help-block">{{ $errors->first('category_id') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('default_id') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="default_id">@lang('general.app.set_as_default') </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <div class="checkbox checkbox-primary">
                                    <input id="checkbox" type="checkbox" name="default_id" value="1" @if (old('default_id') == 1)) checked="" @endif >
                                    <label for="checkbox"></label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('is_negative') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="is_negative">@lang('categories.is_negative') </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <div class="checkbox checkbox-primary">
                                    <input id="is_negative" type="checkbox" name="is_negative" value="1" @if (old('is_negative') == 1)) checked="" @endif >
                                    <label for="is_negative"></label>
                                </div>
                            </div>
                        </div>

                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-2">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <button type="submit" class="btn btn-success">@lang('general.form.save')</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/bookingTypes/bookingTypes_delete.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-11 col-sm-11 col-xs-12">
                            <h2>@lang('general.app.confirm.delete.title') </h2>
                        </div>
                        <div class="col-md-1 col-sm-1 col-xs-12 text-right">
                            <a href="{{route('bookingTypes.index')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> @lang('general.nav.back') </a>
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <p>@lang('general.app.confirm.delete.question') <strong>{{$bookingType->name}}?</strong></p>

                    <form method="POST" action="{{ route('bookingTypes.destroy', ['id' => $bookingType->id]) }}">
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">@lang('general.form.delete') <strong>{{$bookingType->name}}</strong></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/bookingTypes/bookingTypes_delete_link.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <h2>@lang('general.app.confirm.delete.title') </h2>
                        </div>
                        <div class="col-md-2 col-sm-2 col-xs-12 text-right">
                            <a href="{{route('bookingTypes.index')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> @lang('general.nav.back') </a>
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <p>@lang('general.app.confirm.delete.question') <strong>{{$category->name}}</strong></p>

                    <form method="POST" action="{{ route('bookingTypes.destroy_link', ['id' => $category->id ]) }}">
                        {{ csrf_field() }}
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <button type="submit" class="btn btn-danger">@lang('general.form.delete') <strong>{{$category->name}}</strong></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/bookingTypes/bookingTypes_edit_link.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <h2>@lang('categories.categories') </h2>
                        </div>
                        <div class="col-md-2 col-sm-2 col-xs-12 text-right">
                            <a href="{{route('bookingTypes.link')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> @lang('general.nav.back') </a>
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <form method="post" action="{{ route('bookingTypes.update_link', ['id' => $category->id]) }}" data-parsley-validate class="form-horizontal form-label-left">
                    {{ csrf_field() }}
                        <div class="form-group">
                            <div class="col-md-2 col-sm-2 col-xs-12">
                                <p class="h4">{{ $category->name }}</p>
                            </div>

                            <div class="col-md-10 col-sm-10 col-xs-12 {{ $errors->has('category') ? ' has-error' : '' }}">
                                <div class="well" style="min-height: 100px;overflow: auto;">
                                    @foreach($bookingTypes as $val)
                                        <div class="checkbox checkbox-primary">
                                            <input id="checkbox{{ $val->id }}" type="checkbox" name="bookingType[]" value="{{ $val->id }}" @if($category_bookingTypes->contains($val->id)) checked="" @endif>
                                            <label for="checkbox{{ $val->id }}">{{ $val->name }}</label>
                                        </div>
                                    @endforeach
                                </div>
                                @if ($errors->has('category'))
                                    <span class="help-block">{{ $errors->first('category') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-2">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <button type="submit" class="btn btn-success">@lang('general.form.save')</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/bookingTypes/bookingTypes_force_delete.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-11 col-sm-11 col-xs-12">
                            <h2>@lang('general.app.confirm.delete.title') </h2>
                        </div>
                        <div class="col-md-1 col-sm-1 col-xs-12 text-right">
                            <a href="{{route('bookingTypes.index')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> @lang('general.nav.back') </a>
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <p>@lang('general.app.confirm.delete.question') <strong>{{$bookingType->name}}?</strong></p>

                    <form method="POST" action="{{ route('bookingTypes.force_delete', ['id' => $bookingType->id]) }}">
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <button type="submit" class="btn btn-danger">@lang('general.form.delete') <strong>{{$bookingType->name}}</strong></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/bookingTypes/bookingTypes_list.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <h2>
                                @if($trashedItems == 1)
                                    @lang('bookingTypes.deleted_bookingTypes')
                                @else
                                    @lang('bookingTypes.bookingTypes')
                                @endif
                            </h2>
                        </div>
                        <div class="col-md-2 col-sm-2 col-xs-12 text-right">
                            @if($trashedItems == 0)
                                <a href="{{route('bookingTypes.create')}}" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> @lang('general.app.create_new') </a>
                            @endif
                            @if($trashedItems == 0 && (isset($countItems) && $countItems > 0))
                                <a href="{{route('bookingTypes.deleted_bookingtypes')}}" class="text-danger"><i class="fa fa-trash fa-lg" title="@lang('general.form.deleted_items')"></i> </a>
                            @elseif($trashedItems == 1)
                                <a href="{{route('bookingTypes.index')}}" class="btn btn-success btn-xs"><i class="fa fa-arrow-left"></i> @lang('general.form.active_items') </a>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>@lang('bookingTypes.bookingType')</th>
                                <th>@lang('bookingTypes.description')</th>
                                <th>@lang('bookingTypes.gb_rek')</th>
                                <th>@lang('bookingTypes.default')</th>
                                @ability('','edit,delete')
                                <th class="action">@lang('bookingTypes.action')</th>
                                @endability
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>@lang('bookingTypes.bookingType')</th>
                                <th>@lang('bookingTypes.description')</th>
                                <th>@lang('bookingTypes.gb_rek')</th>
                                <th>@lang('bookingTypes.default')</th>
                                @ability('','edit,delete')
                                <th class="action">@lang('bookingTypes.action')</th>
                                @endability
                            </tr>
                        </tfoot>
                        <tbody>
                            @if (count($bookingTypes))
                                @foreach($bookingTypes as $row)
                                <tr>
                                    <td>{{$row->name}}</td>
                                    <td>{{$row->description}}</td>
                                    <td>{{$row->gb_rek}}</td>
                                    <td>@if($row->set_default == 1) <i class="fa fa-check-square-o fa-lg text-success"></i> @else <i class="fa fa-times fa-lg text-danger"></i> @endif</td>
                                    @ability('','edit,delete')
                                    <td class="action">
                                        @permission(('edit'))
                                            @if($trashedItems == 0)
                                                <a href="{{ route('bookingTypes.edit', ['id' => $row->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="@lang('general.form.edit')"></i> </a>
                                            @endif
                                        @endpermission
                                        @permission(('delete'))
                                            @if($trashedItems == 1)
                                                <a href="{{ route('bookingTypes.activate', ['id' => $row->id]) }}" class="btn btn-success btn-xs"><i class="fa fa-thumbs-up" title="@lang('general.form.activate')"></i> </a>
                                                <a href="{{ route('bookingTypes.delete', ['id' => $row->id]) }}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o" title="@lang('general.form.activate')"></i> </a>
                                            @else
                                                <a href="{{ route('bookingTypes.show', ['id' => $row->id]) }}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o" title="@lang('general.form.delete')"></i> </a>
                                            @endif
                                        @endpermission
                                    </td>
                                    @endability
                                </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop