routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', [
    'uses' => 'HomeController@index',
    'as' => 'login',
    ])->middleware('auth');

Route::group(['prefix' => LaravelLocalization::setLocale(),'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]], function(){
    Route::group(['prefix' => 'admin','middleware' => 'auth','namespace' => 'Admin'],function(){
        Route::resource('home', 'DashboardController');

        // Categories routes
        Route::get('categories/link', 'CategoriesController@link')->name('categories.link');
        Route::get('categories/create_link', 'CategoriesController@create_link')->name('categories.create_link');
        Route::post('categories/store_link', 'CategoriesController@store_link')->name('categories.store_link');
        Route::get('categories/edit_link/{id}', 'CategoriesController@edit_link')->name('categories.edit_link');
        Route::post('categories/update_link/{id}', 'CategoriesController@update_link')->name('categories.update_link');
        Route::get('categories/show_link/{id}', 'CategoriesController@show_link')->name('categories.show_link');
        Route::post('categories/delete_link/{id}', 'CategoriesController@destroy_link')->name('categories.destroy_link');
        Route::get('categories/activate/{id}', 'CategoriesController@activate')->name('categories.activate');
        Route::get('categories/delete/{id}', 'CategoriesController@delete')->name('categories.delete');
        Route::post('categories/force_delete/{id}', 'CategoriesController@force_delete')->name('categories.force_delete');
        Route::get('deleted_categories', 'CategoriesController@list_deleted')->name('categories.deleted_categories');
        Route::resource('categories', 'CategoriesController');

        // Headcategories routes
        Route::get('headCategories/activate/{id}', 'HeadCategoriesController@activate')->name('headCategories.activate');
        Route::get('headCategories/delete/{id}', 'HeadCategoriesController@delete')->name('headCategories.delete');
        Route::post('headCategories/force_delete/{id}', 'HeadCategoriesController@force_delete')->name('headCategories.force_delete');
        Route::get('deleted_headcategories', 'HeadCategoriesController@list_deleted')->name('headCategories.deleted_headcategories');
        Route::resource('headCategories', 'HeadCategoriesController');

        // BookingTypes routes
        Route::get('bookingTypes/activate/{id}', 'BookingTypesController@activate')->name('bookingTypes.activate');
        Route::get('bookingTypes/link', 'BookingTypesController@link')->name('bookingTypes.link');
        Route::get('bookingTypes/create_link', 'BookingTypesController@create_link')->name('bookingTypes.create_link');
        Route::post('bookingTypes/store_link', 'BookingTypesController@store_link')->name('bookingTypes.store_link');
        Route::get('bookingTypes/edit_link/{id}', 'BookingTypesController@edit_link')->name('bookingTypes.edit_link');
        Route::post('bookingTypes/update_link/{id}', 'BookingTypesController@update_link')->name('bookingTypes.update_link');
        Route::get('bookingTypes/show_link/{id}', 'BookingTypesController@show_link')->name('bookingTypes.show_link');
        Route::post('bookingTypes/destroy_link/{id}', 'BookingTypesController@destroy_link')->name('bookingTypes.destroy_link');
        Route::get('bookingTypes/activate/{id}', 'BookingTypesController@activate')->name('bookingTypes.activate');
        Route::get('bookingTypes/delete/{id}', 'BookingTypesController@delete')->name('bookingTypes.delete');
        Route::post('bookingTypes/force_delete/{id}', 'BookingTypesController@force_delete')->name('bookingTypes.force_delete');
        Route::get('deleted_bookingtypes', 'BookingTypesController@list_deleted')->name('bookingTypes.deleted_bookingtypes');
        Route::resource('bookingTypes', 'BookingTypesController', ['except' => 'delete_link']);

        // settings routes
        Route::resource('settings', 'SettingsController');
        Route::resource('settingTypes', 'SettingTypesController');

        // transactions / mutations routes
        Route::get('transactions/create/{id}', 'TransactionsController@create')->name('transactions.create');
        Route::get('transactions/show/{id}', 'TransactionsController@show')->name('transactions.show');
        Route::get('transactions/pdf/{id}', 'TransactionsController@pdf')->name('transactions.pdf');
        Route::get('mutation_quarters', 'TransactionsController@mutation_quarters')->name('transactions.mutation_quarters');
        Route::post('mutation_quarters', 'TransactionsController@getMutation_quarters')->name('transactions.get_mutation_quarters');
        Route::get('mutations', 'TransactionsController@mutations')->name('transactions.mutations');
        Route::post('mutations', 'TransactionsController@getMutations')->name('transactions.get_mutations');
        Route::resource('transactions', 'TransactionsController', ['except' => 'create']);

        // users, roles and permissions routes
        Route::get('users/activate/{id}', 'UsersController@activate')->name('users.activate');
        Route::get('users/activate_app_user/{id}', 'UsersController@activate_app_user')->name('users.activate_app_user');
        Route::get('users_app', 'UsersController@index_app')->name('users.index_app');
        Route::get('users/users_app/{id}', 'UsersController@show_app')->name('users.show_app');
        Route::get('create_app_user', 'UsersController@create_app_user')->name('users.create_app_user');
        Route::get('users_app/{id}/edit', 'UsersController@edit_app_user')->name('users.edit_app_user');
        Route::post('users/store_app_user', 'UsersController@store_app_user')->name('users.store_app_user');
        Route::get('users/delete/{id}', 'UsersController@delete')->name('users.delete');
        Route::get('users/delete_app_user/{id}', 'UsersController@delete_app_user')->name('users.delete_app_user');
        Route::get('users_app/{id}', 'UsersController@show_app_user')->name('users.show_app');
        Route::post('users_app/{id}', 'UsersController@destroy_app_user')->name('users.destroy_app');
        Route::post('users/update_app_user/{id}', 'UsersController@update_app_user')->name('users.update_app_user');
        Route::post('users/force_delete/{id}', 'UsersController@force_delete')->name('users.force_delete');
        Route::post('users/force_delete_app_user/{id}', 'UsersController@force_delete_app_user')->name('users.force_delete_app_user');
        Route::get('deleted_users', 'UsersController@list_deleted')->name('users.deleted_users');
        Route::get('deleted_app_users', 'UsersController@list_app_users_deleted')->name('users.deleted_app_users');
        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController');
        Route::resource('permissions', 'PermissionsController');

        // Information page routes
        Route::resource('information', 'InformationController');
        Route::get('information_page', 'InformationController@info_page')->name('information.information_page');
    });

    // User routes
    $this->get('admin/new_registrations', 'Admin\UsersController@newRegistrations')->name('users.newRegistrations');
    $this->get('admin/activate_new_user/{id}', 'Admin\UsersController@activateNewUser')->name('users.activateNewUser');

    // Change password routes
    $this->get('admin/changepass', 'Admin\UsersController@changePassword')->name('changepass')->middleware('auth');
    $this->post('admin/changepass', 'Admin\UsersController@updatePassword');

    // Authentication Routes...
    $this->get('admin/login', 'Auth\LoginController@showLoginForm')->name('login');
    $this->post('admin/login', 'Auth\LoginController@login');
    $this->get('admin/logout', 'Auth\LoginController@logout')->name('logout');

    // Password Reset Routes...
    $this->get('admin/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    $this->post('admin/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('admin/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.token');
    $this->post('admin/password/reset', 'Auth\ResetPasswordController@reset');
});

app/Models/Permission.php
<?php

namespace OptiCore\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Permission extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'display_name',
        'description',
    ];

    public function roles() 
    {
    	return $this->belongsToMany('OptiCore\Models\Role','permission_role','permission_id','role_id');
    }
}

app/Http/Controllers/Admin/PermissionsController.php
<?php

namespace OptiCore\Http\Controllers\Admin;

use OptiCore\Models\Role;
use OptiCore\Models\Permission;
use Illuminate\Http\Request;
use OptiCore\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class PermissionsController extends Controller
{
    /**
     * Instantiate a new PermissionsController instance.
     */
    public function __construct()
    {
        $this->middleware('permission:users');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::all();

        $params = [
            'title' => 'Permissies Lijst',
            'permissions' => $permissions,
        ];

        return view('admin.permissions.permissions_list')->with($params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();

        $params = [
            'title' => 'Create Permission',
            'permissions' => $permissions,
        ];
        
        return view('admin.permissions.permissions_create')->with($params);   
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:permissions',
            'display_name' => 'required|unique:permissions,display_name,',
            'description' => 'required',
        ]);
        
        $permission = Permission::create([
            'name' => strtolower($request->input('name')),
            'display_name' => $request->input('display_name'),
            'description' => $request->input('description'),
        ]);
        
        return redirect()->route('permissions.index')->with('success', trans('general.form.flash.created',['name' => $permission->name]));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try
        {
            $permission = Permission::findOrFail($id);

            $params = [
            'title' => 'Delete permission',
            'permission' => $permission,
            ];

            return view('admin.permissions.permissions_delete')->with($params);  
        }
        
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try
        {
            $permission = Permission::findOrFail($id);

            $params = [
                'title' => 'Edit permission',
                'permission' => $permission
            ];

            return view('admin.permissions.permissions_edit')->with($params);
        }
        
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try
        {
            $this->validate($request, [
                'name' => 'required|unique:permissions,name,'.$id,
                'display_name' => 'required|unique:permissions,display_name,',
                'description' => 'required',
            ]);
            
            $permission = Permission::findOrFail($id);
            
            $permission->name = strtolower($request->input('name'));
            $permission->display_name = $request->input('display_name');
            $permission->description = $request->input('description');

            $permission->save();

            return redirect()->route('permissions.index')->with('success', trans('general.form.flash.updated',['name' => $permission->name]));
        }
        
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try
        {
            $permission = Permission::findOrFail($id);

            $permission->delete();

            return redirect()->route('permissions.index')->with('success', trans('general.form.flash.deleted',['name' => $permission->name]));
        }
        
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }
}

resources/views/admin/permissions/permissions_create.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <h2>@lang('permissions.create_permission') </h2>
                        </div>
                        <div class="col-md-2 col-sm-2 col-xs-12 text-right">
                            <a href="{{route('permissions.index')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> @lang('general.nav.back') </a>
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <br />
                    <form method="post" action="{{ route('permissions.store') }}" data-parsley-validate class="form-horizontal form-label-left">

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="permission">@lang('permissions.permission') <span class="required">*</span>
                            </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <input type="text" value="{{ Request::old('name') ?: '' }}" id="name" name="name" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('name'))
                                <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="display_name">@lang('permissions.display_name') <span class="required">*</span>
                            </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <input type="text" value="{{ Request::old('display_name') ?: '' }}" id="display_name" name="display_name" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('display_name'))
                                    <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="description">@lang('permissions.description') <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('description') ?: '' }}" id="description" name="description" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('description'))
                                <span class="help-block">{{ $errors->first('description') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-2">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <button type="submit" class="btn btn-success">@lang('general.form.save')</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/permissions/permissions_delete.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <h2>@lang('general.app.confirm.delete.title') </h2>
                        </div>
                        <div class="col-md-2 col-sm-2 col-xs-12 text-right">
                            <a href="{{route('permissions.index')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> @lang('general.nav.back') </a>
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <p>@lang('general.app.confirm.delete.question') <strong>{{$permission->name}}?</strong></p>

                    <form method="POST" action="{{ route('permissions.destroy', ['id' => $permission->id]) }}">
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">@lang('general.form.delete') <strong>{{$permission->name}}</strong></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/permissions/permissions_edit.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <h2>@lang('permissions.edit_permission') </h2>
                        </div>
                        <div class="col-md-2 col-sm-2 col-xs-12 text-right">
                            <a href="{{route('permissions.index')}}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> @lang('general.nav.back') </a>
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <br />

                    <form method="post" action="{{ route('permissions.update', ['id' => $permission->id]) }}" data-parsley-validate class="form-horizontal form-label-left">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="name">@lang('permissions.name') <span class="required">*</span>
                            </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <input type="text" value="{{$permission->name}}" id="name" name="name" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('name'))
                                <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="display_name">@lang('permissions.display_name') <span class="required">*</span>
                            </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <input type="text" value="{{$permission->display_name}}" id="display_name" name="display_name" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('name'))
                                <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label class="col-sm-2 col-form-label col-xs-12" for="description">@lang('permissions.description') <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{$permission->description}}" id="description" name="description" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('description'))
                                <span class="help-block">{{ $errors->first('description') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-2">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <input name="_method" type="hidden" value="PUT">
                                <button type="submit" class="btn btn-success">@lang('general.form.save_changes')</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/permissions/permissions_list.blade.php
@extends('templates.admin.layout')

@section('content')
<div class="">

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <h2>@lang('permissions.permissions') </h2>
                        </div>
                        <div class="col-md-2 col-sm-2 col-xs-12 text-right">
                            <a href="{{route('permissions.create')}}" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> @lang('general.app.create_new') </a>
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>@lang('permissions.name')</th>
                                <th>@lang('permissions.display_name')</th>
                                <th>@lang('permissions.description')</th>
                                @ability('','edit,delete')
                                <th class="action">@lang('permissions.action')</th>
                                @endability
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>@lang('permissions.name')</th>
                                <th>@lang('permissions.display_name')</th>
                                <th>@lang('permissions.description')</th>
                                @ability('','edit,delete')
                                <th class="action">@lang('permissions.action')</th>
                                @endability
                            </tr>
                        </tfoot>
                        <tbody>
                            @if (count($permissions))
                            @foreach($permissions as $row)
                            <tr>
                                <td>{{$row->name}}</td>
                                <td>{{$row->display_name}}</td>
                                <td>{{$row->description}}</td>
                                @ability('','edit,delete')
                                <td class="action">
                                    @permission(('edit'))
                                    <a href="{{ route('permissions.edit', ['id' => $row->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="Edit"></i> </a>
                                    @endpermission
                                    @permission(('delete'))
                                    <a href="{{ route('permissions.show', ['id' => $row->id]) }}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o" title="Delete"></i> </a>
                                    @endpermission
                                </td>
                                @endability
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop